# 上线配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cwt
    url: jdbc:mysql://windows:3306/user_center?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
  session:
    timeout: 86400
server:
  port: 80
  servlet:
    context-path: /api